[theme]
primaryColor = "#001F54"             # Navy (for buttons, highlights)
backgroundColor = "#FFFFFF"           # White page background
secondaryBackgroundColor = "#F5F5F5"  # Light Grey for sidebar/background sections
textColor = "#001F54"                 # Navy text color
font = "serif"                        # Cambria falls under serif fonts

